version: '3'

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: requirements/wordpress/
    image: wordpress
    volumes:
      - wordpress-data:/var/www/html
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file:
      - .env

  nginx:
    build: requirements/nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    env_file:
      - .env
      
networks:
  inception:
    driver: bridge

volumes:
  db-data:
    driver_opts:
      type: none
      device: ${HOME}/data/db-data
      o: bind
  wordpress-data:
    driver_opts:
      type: none
      device: ${HOME}/data/wordpress-data
      o: bind
